/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [2.4MB] > /home/poliziacantonale/Downloads/romrom/scene-transformed.glb [1.32MB] (45%)
Author: Neberkenezer (https://sketchfab.com/neberkenezer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ccity-building-set-1-a2d5c7bfcc2148fb8994864c43dfcc97
Title: CCity Building Set 1
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ 
  scale = 0.0005, 
  position = [0, 0, 0], // Default position at origin
  rotation = [0, 0, 0], // Default rotation
  ...props 
}) {
  const { nodes, materials } = useGLTF('/city/scene-transformed.glb')
  return (
    <group 
      {...props} 
      scale={scale} 
      position={position}
      rotation={rotation}
      dispose={null}
    >
      <mesh geometry={nodes.pCube2_Paramount_0.geometry} material={materials.Paramount} position={[-21800, 170, -8650]} />
      <mesh geometry={nodes.polySurface3_Paramount1GLOW_0.geometry} material={materials.Paramount1GLOW} position={[-22322.879, 4.84, -8661.039]} scale={1.026} />
      <mesh geometry={nodes.pCube11_FillerBuildings1_0.geometry} material={materials.FillerBuildings1} position={[-18050, 170, -8450]} scale={[0.663, 1, 0.674]} />
      <mesh geometry={nodes.polySurface20_FillerBuildings1GLOW_0.geometry} material={materials.FillerBuildings1GLOW} position={[-16505.207, 810.33, -8439.369]} scale={[2.701, 1.237, 0.728]} />
      <mesh geometry={nodes.polySurface260_CityProps_0.geometry} material={materials.CityProps} position={[-15050, 0, -6400]} />
      <mesh geometry={nodes.polySurface791_CityProps1GLOW_0.geometry} material={materials.CityProps1GLOW} position={[-15050, 0, -6400]} />
      <mesh geometry={nodes.polySurface739_RedGLOW_0.geometry} material={materials.RedGLOW} position={[-15050, 0, -6400]} />
      <mesh geometry={nodes.polySurface739_GreenGlow_0.geometry} material={materials.GreenGlow} position={[-15050, 0, -7900]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.polySurface839_WhiteGlow1_0.geometry} material={materials.WhiteGlow1} position={[-22656.896, 0, 7394.786]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.pasted__ALPHA_OPAQUE_INT_BTM_elise_0.geometry} material={materials.elise} position={[-12163.745, 120.334, -8245.036]} rotation={[0, 1.429, 0]} scale={139.53} />
      <mesh geometry={nodes.pasted__ALPHA_OPAQUE_RUBBER_WFR_Tire_0.geometry} material={materials.Tire} position={[-12163.745, 120.334, -8245.036]} rotation={[0, 1.429, 0]} scale={139.53} />
      <mesh geometry={nodes.LM_Basketball9_Basketball_0.geometry} material={materials.Basketball} />
      <mesh geometry={nodes.LM_Clinic2_Clinic_0.geometry} material={materials.Clinic} />
      <mesh geometry={nodes.BD_ConcreteBlock1_RoadsGround_0.geometry} material={materials.RoadsGround} />
      <mesh geometry={nodes.LMProjects2_pasted__group65_pasted__pCube39_LMProjects1GLOW_0.geometry} material={materials.LMProjects1GLOW} />
      <mesh geometry={nodes.LMProjects2_pasted__group65_pasted__pCube40_LMProjects_0.geometry} material={materials.LMProjects} />
      <mesh geometry={nodes.polySurface836_WhiteGlow_0.geometry} material={materials.WhiteGlow} position={[-34950.596, 2071.557, -7859.899]} rotation={[Math.PI, Math.PI / 2, 0]} scale={0.868} />
      <mesh geometry={nodes.pasted__pPlane94_Laundrymat_0.geometry} material={materials.Laundrymat} position={[-12750, 29.253, -9200]} />
      <mesh geometry={nodes.pasted__pCube1_FishFactory_0.geometry} material={materials.FishFactory} position={[-5250, 425, -9100]} />
      <mesh geometry={nodes.pasted__pCube27_FishFactory1GLOW_0.geometry} material={materials.FishFactory1GLOW} position={[-2375.839, 1106.124, -8212.11]} scale={[0.264, 0.649, 0.261]} />
      <mesh geometry={nodes.pasted__pCube80_Pawnshop_0.geometry} material={materials.Pawnshop} position={[-25100, 450, -9050]} />
      <mesh geometry={nodes.pasted__loftedSurface3_Pawnshop1GLOW_0.geometry} material={materials.Pawnshop1GLOW} position={[-25100, 0, -8950]} />
    </group>
  )
}

useGLTF.preload('/city/scene-transformed.glb')
